### ISSUE TITLE
[Feature Request] Add pagination options!

### ISSUE THREAD

**Issue by molaeiali** [VassilisPallas/mongoose-fuzzy-searching#64] opened 2020-08-20 14:31 UTC
Ability to skip and limiting and counting the results would be great as mongoose provides them it self in find() function.

**Comment by VassilisPallas** [comment] 2020-10-31 14:31
Duplicate of https://github.com/VassilisPallas/mongoose-fuzzy-searching/issues/60

**Closed by VassilisPallas** 2020-10-31 14:31 UTC
